name: CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm test:coverage

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
      - run: pnpm build:demo

  deploy-preview:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: pages
      cancel-in-progress: false

    environment:
      name: github-preview
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build:demo
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './demo'
      - uses: actions/deploy-pages@v4
        id: deployment
